BASE_PATH=/home/$ADMIN_USER_VAR

SCRIPTS_PATH=$BASE_PATH/.scripts
BIN_PATH=$BASE_PATH/.bin

SUPERVISOR_CONF_PATH=$BASE_PATH/conf/supervisor
SUPERVISOR_SOCK_PATH=/var/run/supervisor.sock

AFTER_LOGIN_SCRIPT_PATH=$SCRIPTS_PATH/after-login.sh